# Generated by Django 3.1.8 on 2021-07-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210705_1520'),
        ('customers', '0002_auto_20210705_2132'),
    ]

    operations = [
    ]
